### ISSUE TITLE
Error when running Virus_total_file 

### ISSUE THREAD

**Issue by Akilan1999** [HWTechClub/Virus-Scanner#8]
## Error occurs when running with files of certain sizes 
```
python3 cli.py --VirusTotalFile gui.py 

Processing File...
Traceback (most recent call last):
  File "cli.py", line 45, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 34, in main
    ScanFile(virustotalfile,Virus_Total_API_key())
  File "../VirusTotal_API/VirusTotal_API_File.py", line 41, in ScanFile
    finalScans = finalReport['scans']		# get scans from report
KeyError: 'scans'
```

**Comment by PC-02** [comment]
Changed wait time for file scanning to be dynamic, issue shouldn't arise. More testing needed though

**Comment by Akilan1999** [comment]
Alright will check it out
